name: Pipiline Heroku
run-name: Execução da pipiline Heroku
on: [push]
jobs:
  Automatizando-Cenarios-Actions:
    runs-on: ubuntu-latest
    permissions: write-all
    strategy:
        matrix:
          browser: [ chromium, firefox, webkit ]
        fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install python 3.12.2
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.2'

      - name: Install Node.js 20.12.0
        uses: actions/setup-node@v4
        with:
          node-version: '20.12.0'

      - name: Install Requirements
        run: |
          python -m pip install --upgrade pip
          pip install -U -r requirements.txt
          sudo npm install @playwright/test
          sudo npx playwright install-deps
          rfbrowser init
          
      - name: Run Testes Heroku
        run: |
            robot -d ./results -v HEADLESS:true -v BROWSER:${{ matrix.browser }}  cenarios

      - name: Upload Tests Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: results-${{ matrix.browser }}
          path: ./results
          if-no-files-found: ignore
          retention-days: 2

      - name: Download Tests Results
        if: always()
        uses: actions/download-artifact@v4
        with:
          name: results-${{ matrix.browser }}

      - name: Send Report
        if: always()
        uses: joonvena/robotframework-reporter-action@v2
        with:
          report_path: results-${{ matrix.browser }}
          gh_access_token: ${{ secrets.GITHUB_TOKEN }}
          show_passed_tests: false